version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petcarex_db
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: